[package]
name = "playground6"
version = "0.1.0"
edition = "2021"

[dependencies]
docx-rs = "0.4.17"
lopdf = "0.35.0"
sqlite = "0.36.1"
strsim = "0.11.1"
iced = { version = "0.13.1", features = ["image"] }
regex = "1.11.1"
rust-bert = "0.23.0"
tch = "^0.17.0"
rfd = "0.15.2"
